// <auto-generated />
namespace CapacitacionMVC.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CapacitacionMVCData_Init_db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CapacitacionMVCData_Init_db));
        
        string IMigrationMetadata.Id
        {
            get { return "201604071936555_CapacitacionMVC.Data_Init_db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
